##
## THIS FILE IS AUTOMATICALLY GENERATED
##     >> DO NOT EDIT MANUALLY <<
##
## @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
## Generated by : ${generator}
## Version      : ${version}
## Date         : ${today}
##

export CQLSH_HOST=${cassandraServerAddress}

<#list udts as entity>
#Install the ${entity} Type
echo "Installing type ${entity}..." 
cqlsh < ${entity}.cql
echo "Type done."
</#list>

<#list entities as entity>
#Install the ${entity} Table
echo "Installing table ${entity}..." 
cqlsh < ${entity}.cql
echo "Table done."

#Create the Solr index
echo "Installing Solr ${entity} index..."
sh install.sh ${solrServerAddress} 8983 solrconfig.xml ${entity}Schema.xml ${keyspace} ${entity?lower_case}

</#list>