//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 12:11:15 PM MYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eclipse.org/emf/2002/Ecore")
package fr.hin.modelgenerator.ecore;
