/*
 * 
 * Nourreddine HOUARI CONFIDENTIAL
 * 
 * All information contained herein is, and remains
 * the property of Nourreddine HOUARI and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Nourreddine HOUARI
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Nourreddine HOUARI.
 * 
 * [2017] Nourreddine HOUARI SA
 * All Rights Reserved.
 */
 
//
// THIS FILE IS AUTOMATICALLY GENERATED
//     >> DO NOT EDIT MANUALLY <<
//
// @author Nourreddine HOUARI (nourreddine.houari@)
// Generated by : ${generator}
// Version      : ${version}
// Date         : ${today}
//

package ${package};

/**
 * Define all the roles for the ${entity.name}'s CRUD services.
 */
public class ${entity.name}Roles {
  // ${entity.name} roles
  public static final String SAVE_${entity.name?upper_case} = "save-${entity.name?lower_case}";
  public static final String READ_${entity.name?upper_case} = "read-${entity.name?lower_case}";
  public static final String COUNT_${entity.name?upper_case} = "count-${entity.name?lower_case}";
  public static final String DELETE_${entity.name?upper_case} = "delete-${entity.name?lower_case}";
  public static final String LIST_${entity.name?upper_case} = "list-${entity.name?lower_case}";
  public static final String SEARCH_${entity.name?upper_case} = "search-${entity.name?lower_case}";
  
   public static final String[] roles = {
      SAVE_${entity.name?upper_case}, 
      READ_${entity.name?upper_case}, 
      COUNT_${entity.name?upper_case}, 
      DELETE_${entity.name?upper_case}, 
      LIST_${entity.name?upper_case}, 
      SEARCH_${entity.name?upper_case}
   };
}
