<!-- 
 @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
 @author Venkaiah Chowdary Koneru <VenkaiahChowdary.Koneru@sicpa.com>
 Generated by : HTML List View
 Version      : 0.0.3
 Date         : Tue Jul 11 11:52:41 MYT 2017
-->

<div class="row mb-5 mt-5">
  <div class="col-md-4">
    <${entity.name?lower_case}-quick-search class="form-group"></${entity.name?lower_case}-quick-search>
  </div>
   <div class="pull-right">
    <button class="btn btn-primary pull-right" ng-click="$ctrl.goToCreate()"><i class="fa fa-plus" aria-hidden="true" translate></i> Create new</button>
    <item-per-page on-change="$ctrl.numberPerPageChange(value)" class="pull-right mr-5"></item-per-page>
  </div>
</div>

<table class="table table-hover table-striped table-bordered">
  <thead>
    <tr>
      <th><!-- Expand icon --></th>
      <#list entity.attributes as attribute>
      <#if !attribute.hasAnnotation("ListHide")>
      <#if attribute.hasAnnotation("SORT")>
      <th>
        <span ng-click="$ctrl.sortBy('${attribute.name}')">
          ${attribute.name}
          <span ng-class="$ctrl.columnOrder('${attribute.name}')?'fa fa-angle-up':'fa fa-angle-down'"></span>
        </span>
      </th>  
      <#else>
      <th>${attribute.name}</th>
      </#if>
      </#if>
      </#list>
      <#if entity.hasAnnotation("AUDIT_AWARE")>
      <th>
        <span ng-click="$ctrl.sortBy('createdBy')">
         {{ 'Created by' | translate }}
          <span ng-class="$ctrl.columnOrder('createdBy')?'fa fa-angle-up':'fa fa-angle-down'"></span>
        </span>
      </th>
      <th>
        <span ng-click="$ctrl.sortBy('createdDate')">
          {{ 'Created date' | translate }}
          <span ng-class="$ctrl.columnOrder('createdDate')?'fa fa-angle-up':'fa fa-angle-down'"></span>
        </span>
      </th>
      <th>
        <span ng-click="$ctrl.sortBy('modifiedBy')">
          {{ 'Modified by' | translate }}
          <span ng-class="$ctrl.columnOrder('modifiedBy')?'fa fa-angle-up':'fa fa-angle-down'"></span>
        </span>
      </th>
      <th>
        <span ng-click="$ctrl.sortBy('modifiedDate')">
          {{ 'Modified date' | translate }}
          <span ng-class="$ctrl.columnOrder('modifiedDate')?'fa fa-angle-up':'fa fa-angle-down'"></span>
        </span>
      </th>
      </#if>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr class="warning" ng-if="$ctrl.${entity.name?lower_case}PageResult.totalElements == 0"><td align="center" colspan="100">No items.</td></tr>
    <tr class="danger" ng-if="$ctrl.error"><td align="center" colspan="100">Error</td></tr>
    
    <tr ng-repeat-start="${entity.name?lower_case} in $ctrl.${entity.name?lower_case}PageResult.list track by $index" ng-class="{even: $index % 2 !== 0, odd: $index % 2 === 0, 'success': ${entity.name?lower_case}.<#list primaryAttributes as primaryAttribute>${primaryAttribute.name}</#list>==$ctrl.selected}">
      <td>
      <span data-toggle="collapse" ng-click="isCollapsed = !isCollapsed" class="more" ng-class="{'collapsed': !isCollapsed}"></span>
      </td>
      <#list entity.attributes as attribute>
      <#if !attribute.hasAnnotation("ListHide")>
      <#if attribute.type = "boolean">
      <td>{{ ${entity.name?lower_case}.${attribute.name}?'true':'false' }}</td>
      <#elseif attribute.type = "Date">
      <td>{{ ${entity.name?lower_case}.${attribute.name} | date }}</td>
      <#elseif attribute.reference & attribute.multiplicity=1>
      <td>
      <#list attribute.model.getAttributesByAnnotation("PK") as primaryAttribute>
      {{ ${entity.name?lower_case}.${attribute.name}.${primaryAttribute.name} }}
      </#list>
      </td>
      <#elseif attribute.enumerate>
      <td><span class="label label-default">{{ ${entity.name?lower_case}.${attribute.name} }}</span></td>
      <#else>
      <td>{{ ${entity.name?lower_case}.${attribute.name} }}</td>
      </#if> 
      </#if> 
      </#list>
      <#if entity.hasAnnotation("AUDIT_AWARE")>
      <td>{{ ${entity.name?lower_case}.createdBy}}</td>
      <td>{{ ${entity.name?lower_case}.createdDate | date : 'yyyy-MM-dd hh:mm:ss'}}</td>
      <td>{{ ${entity.name?lower_case}.modifiedBy}}</td>
      <td>{{ ${entity.name?lower_case}.modifiedDate | date : 'yyyy-MM-dd hh:mm:ss'}}</td>
      </#if>    
      <td>
        <span ng-if="!$ctrl.hideEdit" class="fa fa-pencil" data-toggle="tooltip" title="Edit this" ng-click="$ctrl.edit${entity.name}(${entity.name?lower_case})"></span>
        <span ng-if="!$ctrl.hideDelete" class="fa fa-trash-o" data-toggle="tooltip" title="Remove this" ng-click="$ctrl.delete${entity.name}(${entity.name?lower_case})"></span>
        <span ng-if="!$ctrl.hideSelect">
          <div class="radio-group">
            <div class="radio">
              <input type="radio" name="radio{{$ctrl.group}}{{$index}}" id="radio{{$ctrl.group}}{{$index}}" ng-click="$ctrl.onItemSelected(${entity.name?lower_case})" ng-checked="${entity.name?lower_case}.<#list primaryAttributes as primaryAttribute>${primaryAttribute.name}</#list>==$ctrl.selected"/>
              <label for="radio{{$ctrl.group}}{{$index}}">
                <span class="radio-input"></span>
              </label>
            </div>
          </div>  
        </span>
        <div class="checkbox" ng-if="!$ctrl.hideSelectMulti">
          <input type="checkbox" name="cb{{$ctrl.group}}{{$index}}" id="cb{{$ctrl.group}}{{$index}}" ng-model="checkValue" ng-change="$ctrl.onItemSelected(${entity.name?lower_case}, checkValue)" ng-checked="${entity.name?lower_case}.<#list primaryAttributes as primaryAttribute>${primaryAttribute.name}</#list>==$ctrl.selected"/>>
          <label for="cb{{$ctrl.group}}{{$index}}"><span></span>
          </label>
        </div>
      </td>
    </tr>
    <tr ng-repeat-end ng-class="{even: $index % 2 !== 0, odd: $index % 2 === 0}">
        <td colspan="9" style="padding: 0">
          <div collapse="isCollapsed" uib-collapse="!isCollapsed">
            <!-- Collapsed content -->
            <div class="panel panel-default">
            <div class="panel-heading"><span class="fa fa-info-circle"></span> ${entity.name} details</div>
            <div class="panel-body">
              <#list entity.attributes as attribute>
              <span class="box-highlight">${attribute.name}</span>
              <#if attribute.type = "boolean">
              <span>{{ ${entity.name?lower_case}.${attribute.name}?'true':'false' }}</span>
              <#elseif attribute.type = "Date">
              <span>{{ ${entity.name?lower_case}.${attribute.name} | date }}</span>
              <#elseif attribute.reference && attribute.multiplicity=1>
              <span>
              <#list attribute.model.getAttributesByAnnotation("PK") as primaryAttribute>
              {{ ${entity.name?lower_case}.${attribute.name}.${primaryAttribute.name} }}
              </#list>
              </span>
              <#elseif attribute.enumerate>
              <span class="label label-default">{{ ${entity.name?lower_case}.${attribute.name} }}</span>
              <#else>
              <span>{{ ${entity.name?lower_case}.${attribute.name} }}</span>
              </#if>
              </#list>
              <#if entity.hasAnnotation("EXTENDABLE")>
              <div class="form-group">
                  <schema-field 
                    type="field.displayType" context="display" 
                    field="field" data="${entity.name?lower_case}.extensions"
                    form="form[field.name]" editing="true"
                    input-width="12" ng-repeat="field in $ctrl.flatSchema">
                  </schema-field>
              </div>
              </#if>   
            </div>
          </div>
          </div>
        </td>
      </tr>
  </tbody>
</table>
<pagination start="$ctrl.${entity.name?lower_case}PageResult.number" total="$ctrl.${entity.name?lower_case}PageResult.totalElements" itemsperpage="$ctrl.${entity.name?lower_case}PageResult.size"
  callback="$ctrl.pagechange({start: start})" ng-if="$ctrl.${entity.name?lower_case}PageResult.list"></pagination>