--
-- THIS FILE IS AUTOMATICALLY GENERATED
--     >> DO NOT EDIT MANUALLY <<
--
-- @author Nourreddine HOUARI (nourreddine.houari@)
-- Generated by : ${generator}
-- Version      : ${version}
-- Date         : ${today}
--
<#if entity.hasAnnotation("UDT")>
DROP TYPE IF EXISTS ${keyspace}.${entity.name?lower_case};
<#else>
DROP TABLE IF EXISTS ${keyspace}.${entity.name?lower_case};
</#if> 

<#if entity.hasAnnotation("UDT")>
CREATE TYPE ${keyspace}.${entity.name?lower_case} ( 
<#else>
CREATE TABLE ${keyspace}.${entity.name?lower_case} ( 
</#if> 
	<#list entity.attributes as attribute>
		<#if attribute.type == "String">
		<#if attribute?index gt 1>,</#if>${attribute.name} text
		<#elseif attribute.type == "byte">
		<#if attribute?index gt 1>,</#if>${attribute.name} int
	    <#elseif attribute.type == "short">
	    <#if attribute?index gt 1>,</#if>${attribute.name} int
	    <#elseif attribute.type == "int">
	    <#if attribute?index gt 1>,</#if>${attribute.name} int
	    <#elseif attribute.type == "long">
	    <#if attribute?index gt 1>,</#if>${attribute.name} bigint
	    <#elseif attribute.type == "float">
	    <#if attribute?index gt 1>,</#if>${attribute.name} float
	    <#elseif attribute.type == "double">
	    <#if attribute?index gt 1>,</#if>${attribute.name} double
	    <#elseif attribute.type == "boolean">
	    <#if attribute?index gt 1>,</#if>${attribute.name} boolean
	    <#elseif attribute.type == "Date">
	   <#if attribute?index gt 1>,</#if> ${attribute.name} timestamp
        <#else>
        <#if attribute.reference>
        <#if attribute.model.hasAnnotation("UDT")>
        <#if attribute?index gt 1>,</#if>${attribute.name} <#if attribute.multiplicity==-1>list<</#if> frozen<${attribute.type}><#if attribute.multiplicity==-1>></#if>  
        <#else>
		<#if !attribute.containment>
 		<#list attribute.model.entity.attributes as foreignAttribute>
    	<#if foreignAttribute.hasAnnotation("PK") || foreignAttribute.hasAnnotation("CC")>
    	<#if foreignAttribute.type == "String">
		<#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} text
		<#elseif foreignAttribute.type == "byte">
		<#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "short">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "int">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "long">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} bigint
	    <#elseif foreignAttribute.type == "float">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} float
	    <#elseif foreignAttribute.type == "double">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} double
	    <#elseif foreignAttribute.type == "boolean">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} boolean
	    <#elseif foreignAttribute.type == "Date">
	    <#if attribute?index gt 1>,</#if>${attribute.name?uncap_first}_${foreignAttribute.name?uncap_first} timestamp
	    </#if>
		</#if>
		</#list>
		</#if>
		</#if>
        </#if>      
	    </#if>
		<#if attribute?index == 0>,</#if>
    </#list>
	<#if entity.hasAnnotation("UDT")>
		);
	<#else>
	<#list relations as relation>
	<#if relation.containment>
    <#list relation.model.entity.attributes as foreignAttribute>
    <#if foreignAttribute.hasAnnotation("PK") || foreignAttribute.hasAnnotation("CC")>
    	<#if foreignAttribute.type == "String">
		,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} text
		<#elseif foreignAttribute.type == "byte">
		,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "short">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "int">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} int
	    <#elseif foreignAttribute.type == "long">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} bigint
	    <#elseif foreignAttribute.type == "float">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} float
	    <#elseif foreignAttribute.type == "double">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} double
	    <#elseif foreignAttribute.type == "boolean">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} boolean
	    <#elseif foreignAttribute.type == "Date">
	    ,${relation.model.name?uncap_first}_${foreignAttribute.name?uncap_first} timestamp
		</#if>
    	
    </#if>
    </#list>
    </#if>
	</#list>
       ,PRIMARY KEY((<#list primaryentity.attributes as attribute>${attribute.name}<#if attribute?has_next>,</#if></#list>)<#if clusteringentity.attributes?size gt 0>,</#if><#list clusteringentity.attributes as attribute> ${attribute.name}<#if attribute?has_next>,</#if></#list>));
	</#if>