--
-- THIS FILE IS AUTOMATICALLY GENERATED
--     >> DO NOT EDIT MANUALLY <<
--
-- @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
-- Generated by : ${generator}
-- Version      : ${version}
-- Date         : ${today}
--

<#function convertJavaToSqlType type>
   <#if type == "String">
    <#return "TEXT">
   <#elseif type == "Date">
    <#return "DATE">
   <#elseif type == "Byte">
    <#return "SMALLINT">
   <#elseif type == "Short">
    <#return "SMALLINT">
   <#elseif type == "Integer">
    <#return "INTEGER">
   <#elseif type == "Long">
    <#return "BIGINT">
   <#elseif type == "Float">
    <#return "REAL">
   <#elseif type == "Double">
    <#return "DOUBLE PRECISION">
   <#elseif type == "Boolean">
    <#return "BOOLEAN">
   <#elseif type == "Character">
    <#return "CHARACTER VARYING(1)">
   <#else>
    <#return type> 
   </#if>
  <#return "">
</#function>

<#list entities as entity>
<#if entity.type == "CLASS">
-- Clean table
DROP TABLE IF EXISTS ${entity.name}${entity_suffix};

-- Create table
CREATE TABLE ${entity.name}${entity_suffix} (
  published             BOOLEAN     NOT NULL DEFAULT FALSE,
  audit                 BYTEA,
  <#list entity.attributes as attribute>
  <#if attribute.enumerate>
  ${attribute.name?lower_case} INTEGER<#sep>,</#sep>
  <#else>
  ${attribute.name?lower_case} ${convertJavaToSqlType(attribute.type)}<#if attribute.hasAnnotation("PK")> PRIMARY KEY</#if><#sep>,</#sep>
  </#if>
  </#list>
);

<#list entity.attributes as attribute>
<#if attribute.hasAnnotation("QUERY")>
-- Index on ${attribute.name}
CREATE INDEX idx_${entity.name?lower_case}_${attribute.name?lower_case} ON ${entity.name}${entity_suffix}(${attribute.name?lower_case});
</#if>
</#list>
</#if>
</#list>