<!-- 
 @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
 @author Venkaiah Chowdary Koneru <VenkaiahChowdary.Koneru@sicpa.com>
 Generated by : ${generator}
 Version      : ${version}
 Date         : ${today}
-->
<section class="content-header">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
  <div class="panel-heading">
  ${entity.name?cap_first}
  </div>
  <div class="panel-body">
  	<form class="form-horizontal" role="form">
    	<div ng-include="'views/generated/${entity.name?lower_case}-form.html'"></div>
    </form>
  </div>
  <div class="panel-footer text-center">
    <md-button class="md-raised" onClick="history.back()">Back</md-button>
    <md-button class="md-raised md-primary" ng-click="save${entity.name?cap_first}()">Save</md-button> 
  </div>  
</div>
</div>
</section> 