<!-- 
 @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
 @author Venkaiah Chowdary Koneru <VenkaiahChowdary.Koneru@sicpa.com>
 Generated by : ${generator}
 Version      : ${version}
 Date         : ${today}
-->

<div>
    
    <!-- Location dialog -->    
    <div class="modal fade" id="locationDialog" tabindex="-1" role="dialog" aria-labelledby="locationDialogLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-  hidden="true">&times;</span></button>
            <h4 class="modal-title" id="locationDialogLabel">Location</h4>
         </div>
         <div class="modal-body">
           <form class="form-horizontal" role="form">
             <!-- div ng-include="'views/generated/map.html'"></div -->
            </form>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
       </div>
    </div>
    
     <div class="row">
        <div class="col-md-12">
            <span class="pull-left"><h3>${entity.name?cap_first}</h3></span><br>
            <md-button class="md-raised md-primary pull-right" ng-click="new${entity.name?cap_first}()"><p class="glyphicon glyphicon-plus-sign"></p> Add ${entity.name?cap_first}</md-button><br>  
        </div>    
    </div>
    
    <div class="row">
        <hr>	
    </div>
    
    <div class="col-md-3 panel-group pull-left" id="accordion" >
      <div ng-include="'views/generated/${entity.name?lower_case}-search.html'"></div>
    </div>
    
    <div class="col-md-9">
     <div ng-include="'views/generated/${entity.name?lower_case}-table.html'"></div>
    </div>

    
</div>