<!-- 
 @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
 Generated by : ${generator}
 Version      : ${version}
 Date         : ${today}
-->

 
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Search</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in">
          <div class="panel-body">
            <#list searchableAttributes as attribute> 
            <#if attribute.type=="Byte" || attribute.type=="Short"|| attribute.type=="Integer"|| attribute.type=="Long"|| attribute.type=="Float"|| attribute.type=="Double"|| attribute.type=="Date">
              <#if attribute.type == "Date">
             <md-input-container class="md-block" flex-gt-sm>
               <label>From ${attribute.name?cap_first}</label>
               <md-datepicker ng-model="$parent.query${entity.name?cap_first}_from${attribute.name?cap_first}"></md-datepicker>
            </md-input-container>
            <md-input-container class="md-block" flex-gt-sm>
               <label>To ${attribute.name?cap_first}</label>
               <md-datepicker ng-model="$parent.query${entity.name?cap_first}_to${attribute.name?cap_first}"></md-datepicker>
            </md-input-container> 
              <#else>
              <md-input-container class="md-block" flex-gt-sm>
               <label>From ${attribute.name?cap_first}</label>
               <input ng-model="$parent.query${entity.name?cap_first}_from${attribute.name?cap_first}">
              </md-input-container>
              <md-input-container class="md-block" flex-gt-sm>
               <label>To ${attribute.name?cap_first}</label>
               <input ng-model="$parent.query${entity.name?cap_first}_to${attribute.name?cap_first}">
              </md-input-container>
    		  </#if> 
		    </#if>
			<#if attribute.type == "Date">
			<md-input-container class="md-block" flex-gt-sm>
               <label>${attribute.name?cap_first}</label>
               <md-datepicker ng-model="$parent.query${entity.name?cap_first}_${attribute.name?uncap_first}"></md-datepicker>
            </md-input-container>
            <#elseif attribute.enumerate>
            <!-- ENUM -->
            <label for="${attribute.name?uncap_first}">${attribute.name?cap_first}</label><br>
	        <select ng-model="$parent.query${entity.name?cap_first}_${attribute.name?uncap_first}">
	    		<option ng-repeat="${attribute.name} in ${attribute.name}_items"
	            value="{{${attribute.name}.label}}">
	        {{${attribute.name}.label}}
	    		</option>
			</select>
			<#else>
            <div class="form-group">
              <md-input-container class="md-block" flex-gt-sm>
               <label>${attribute.name?cap_first}</label>
               <input ng-model="$parent.query${entity.name?cap_first}_${attribute.name?uncap_first}">
              </md-input-container>	
             </div>
    	    </#if>
		    </#list>
		    <md-button class="md-raised pull-right" ng-click="refresh${entity.name?cap_first}Query()">Search</md-button>
          </div> 
        </div>
      </div> 
