<!-- 
 @author Nourreddine HOUARI (nourreddine.houari@sicpa.com)
 @author Venkaiah Chowdary Koneru <VenkaiahChowdary.Koneru@sicpa.com>
 Generated by : ${generator}
 Version      : ${version}
 Date         : ${today}
-->
<table class="table table-hover table-striped table-bordered">
  <thead>
    <tr>
      <#list entity.attributes as attribute> 
      <#if !(attribute.hasAnnotation("UUID") || attribute.hasAnnotation("AUTO") || attribute.getMultiplicity()==-1 || attribute.hasAnnotation("ListHide"))>
      <th>${attribute.name?cap_first}</th>
      </#if>
      </#list> 
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr ng-repeat="${entity.name?lower_case} in $ctrl.${entity.name?lower_case}s" >
    <!-- tr dir-paginate="${entity.name?lower_case} in ${entity.name?lower_case}s | itemsPerPage: ${entity.name?lower_case}sPerPage" total-items="total${entity.name?cap_first}s" current-page="${entity.name?lower_case}Pagination.current" -->
    <#list entity.attributes as attribute>
    <#if !(attribute.hasAnnotation("UUID") || attribute.hasAnnotation("AUTO") || attribute.getMultiplicity()==-1 || attribute.hasAnnotation("ListHide"))>
    <#if attribute.type=="Date">
     <td>{{ $ctrl.convertDate(${entity.name?lower_case}.${attribute.name?uncap_first}) }}</td>
     <#elseif attribute.reference>
     <td><a href="#/${attribute.model.name?lower_case}/view/<#list attribute.model.getAttributesByAnnotation("PK") as pkattribute>{{ ${entity.name?lower_case}.${attribute.name?uncap_first}DTO.${pkattribute.name} }}<#sep>/<#/sep></#list>"><#list attribute.model.getAttributesByAnnotation("PK") as pkattribute> {{ ${entity.name?lower_case}.${attribute.name?uncap_first}DTO.${pkattribute.name} }} <#sep>,<#/sep></#list></a></td>
     <#else>  
     <td>{{ ${entity.name?lower_case}.${attribute.name?uncap_first} }}</td>
     </#if>
     </#if>
     </#list>
     <td>
       <span class="fa fa-info-circle" data-toggle="tooltip" title="View details" ng-click="$ctrl.view${entity.name?cap_first}(${entity.name?lower_case})"></span>
       <span class="fa fa-pencil" data-toggle="tooltip" title="Edit this" ng-click="$ctrl.edit${entity.name?cap_first}(${entity.name?lower_case})"></span>
       <span class="fa fa-trash-o" data-toggle="tooltip" title="Remove this" ng-click="$ctrl.delete${entity.name?cap_first}(${entity.name?lower_case})"></span>
     </td>
   </tr>
  </tbody>     
</table>