<#assign aDateTime = .now>
<#assign aDate = aDateTime?date>
/*
 * Author   :	Nourreddine HOUARI <nourreddine.houari@>
 * 				Koneru, Venkaiah Chowdary <VenkaiahChowdary.Koneru@> 
 *
 * Date     : 	${aDate?string.medium} 
 * 
 * File     : 	GenericEntityDTOTransformer.java 
 * 
 * Copyright (c) ${aDate?string.yyyy} houari_nourreddine Sdn Bhd, All rights reserved.                   
 */
package ${package};

/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 *     >> DO NOT EDIT MANUALLY <<
 * <br><br>
 * Generated by : ${generator}<br>
 * Version      : ${version}<br>
 * Date         : ${aDate?string.medium}<br>
 * <br>
 * @param <DTO>
 * @param <T>
 * 
 * @author Nourreddine HOUARI <nourreddine.houari@>
 * @author Koneru, Venkaiah Chowdary <VenkaiahChowdary.Koneru@>
 * 
 */
public interface GenericEntityDTOTransformer<DTO, T> {
	
	/**
	 * Copies the data from {@link DTO} object to {@link T} object.
	 *  
	 * @param dto 
	 * @param entity
	 */
	void transformDtoToEntity(DTO dto, T entity);
	
	/**
	 * Copies the data from {@link T} object to {@link DTO} object.
	 *  
	 * @param entity 
	 * @param dto
	 */
	void transformEntityToDto(T entity, DTO dto);
}